"""adding accounts tables

Revision ID: 09cc745a9cab
Revises: 57f260f40dee
Create Date: 2026-04-11 15:29:20.448091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09cc745a9cab'
down_revision: Union[str, Sequence[str], None] = '57f260f40dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('SAVINGS', 'CREDIT', 'CASH', 'EMI', 'LOAN', 'WALLET', name='accounttype'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user'), 'accounts', ['user'], unique=False)
    op.create_table('credit_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('billed_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unbilled_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_installment', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('balance_installment', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('installment_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_accounts')
    op.drop_table('credit_accounts')
    op.drop_index(op.f('ix_accounts_user'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
